main: net.lotrcraft.minepermit.MinePermit
author: Numenorean95
name: MinePermit
version: 1.1
website: http://lotrcraft.net/plugins/minepermit

commands:
    permit:
        description: List of Commands
        aliases: p
        usage: |
            /<command> - List of commands
            /<command> buy [id/"all"] - Buys permit
            /<command> cost [id] - Display cost of certain permit. Leave out id to display price for universal permit
            /<command> view {id} - Displays remaining time for permit. Leave out id to display all owned permits

permissions:
    MinePermit.exempt:
        description: Exempts player from mining permit requirements
        default: op
